sudo: required
services:
    - docker

before_install:
    - docker build -t gerioo/docker-react -f Dockerfile.dev . 

script:
    - docker run -e CI=true gerioo/docker-react npm run test -- --coverage
    

